version: '2'
services:
  rails:
    build: .
    image: my/rails5.1
    container_name: 'rails'
    ports:
      - "80:3000"
    volumes:
      - rails-data:/usr/local/src
      # exclude volumes
      - /usr/local/src/app/vendor
      - /usr/local/src/app/tmp
      - /usr/local/src/app/log

volumes:
  rails-data:
    driver_opts:
      type: none
      device: ${PWD}/src/
      o: bind
